name: Java CI - Compile & Run with JavaFX 21.0.7

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21.0.7
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21.0.7'

    - name: Download and unzip JavaFX 21.0.7 SDK manually
      run: |
        wget https://download2.gluonhq.com/javafx/21.0.7/javafx-sdk-21.0.7_linux-x64_bin-sdk.zip -O javafx-sdk.zip
        unzip javafx-sdk.zip
        ls -l javafx-sdk-21.0.7/lib

    - name: Compile Java files with JavaFX
      run: |
        mkdir -p out
        javac --module-path javafx-sdk-21.0.7/lib --add-modules javafx.controls,javafx.fxml -d out $(find src -name "*.java")

    - name: Run Java program with JavaFX
      run: |
        java --module-path javafx-sdk-21.0.7/lib --add-modules javafx.controls,javafx.fxml -cp out flappybird.Main
