name: Java CI - Compile & Run with JavaFX 21.0.7

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21.0.7
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21.0.7'

    - name: Unzip JavaFX SDK from local file
      run: |
        unzip libs/javafx-sdk.zip -d libs
        ls -l libs

    - name: Compile Java files with JavaFX
      run: |
        mkdir -p out
        javac --module-path libs/javafx-sdk-21.0.7/lib \
              --add-modules javafx.controls,javafx.fxml,javafx.media \
              -d out $(find src -name "*.java")

    - name: Run Java program with JavaFX
      run: |
        java --module-path libs/javafx-sdk-21.0.7/lib \
             --add-modules javafx.controls,javafx.fxml,javafx.media \
             -cp out flappybird.Main
