name: Java CI - Manual compile & run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Compile Java files
      run: |
        mkdir -p out
        javac -d out $(find src -name "*.java")

    - name: Run Java program
      run: java -cp out flappybird.Main
