name: Java CI with Java 21

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
           distribution: 'temurin'
           java-version: '21'


    - name: Verify Java version
      run: java -version

    - name: Compile project
      run: javac -version
